name: slugify
version: 0.2.0
description: Converts strings into slugs, for pretty URLs
author: kameleon83
homepage: https://github.com/kameleon83/slugify
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dev_dependencies:
  test: ^1.5.3
